### PR TITLE
Added support working for i3 and added few logos

### PR DESCRIPTION
**Pull request by dark-steveneq**
I finally managed to get it working. It was simple. If `XDG_CURRENT_DESKTOP` isn't specified, execute `ps x` witch lists all running processes, then just check if process of i3 for example is present, modify variables `de` and `deVerCmd`.

### CODE REVIEW

**Comment by MedzikUser** [comment]
dawaj pieniądze

**Comment by MedzikUser** [comment]
@rafal06 forced me to write this

**Comment by rafal06** [comment]
> @rafal06 forced me to write this

image

**Comment by MedzikUser** [comment]
> > @rafal06 forced me to write this
> 
> image

they tracked me down

**Comment by rafal06** [comment]
Um, this would require some modifications in order to add support for other WMs. Also, there are some unnecessary changes, for example a removed newline. Also, for the future, please don't include other, unrelated changes in 1 PR, in this case the logos. You can make 2 separate PRs for this.

But this project is dead anyway, so I don't think I'll accept any new PRs from now on. Honestly, it was created as a joke in the first place.

Either way, if you really like it, you can maintain your own fork, and add features as you like.

**Pull request closed without merging**
